// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVs1CICwcZQhGfD1ELWjJtqR4WZtS5Jok',
    appId: '1:368043621724:web:6d335ef97df65e07ee1599',
    messagingSenderId: '368043621724',
    projectId: 'parentapp-kjs',
    authDomain: 'parentapp-kjs.firebaseapp.com',
    storageBucket: 'parentapp-kjs.appspot.com',
    measurementId: 'G-BTC25TVQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_B_MW8CfBiiuQ4q0r1rIgP0s558-WhI',
    appId: '1:368043621724:android:a7d09c63c2c7aa6cee1599',
    messagingSenderId: '368043621724',
    projectId: 'parentapp-kjs',
    storageBucket: 'parentapp-kjs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVTiOGd1n91sjMr-95k2XdZvcpWPltPhk',
    appId: '1:368043621724:ios:b9dadcd392ab7148ee1599',
    messagingSenderId: '368043621724',
    projectId: 'parentapp-kjs',
    storageBucket: 'parentapp-kjs.appspot.com',
    iosClientId: '368043621724-ev2ubshsh56m32h4f9it3jijrgfa4qrb.apps.googleusercontent.com',
    iosBundleId: 'br.com.kevennyjs.parentapp',
  );
}
